### ISSUE TITLE
Страница аналитики

### ISSUE THREAD

**Issue by Yxine** [cinic/bcs-am#8]
На странице аналитики пагинация общая, а не разделяемая для трех подразделов.

**Comment by cinic** [comment]
@Yxine , Так она там общая. В таб специально не вносил её. Просто в макете был заголовок над ней.

**Comment by cinic** [comment]
![bcs broker landing page - structured bonds 2015-10-07 11-56-37](https://cloud.githubusercontent.com/assets/67061/10333136/9173f954-6cea-11e5-97e8-a5b9a6cd5e9d.jpg)

**Comment by Yxine** [comment]
![pagination](https://cloud.githubusercontent.com/assets/1074879/10335552/481ce0a8-6cfa-11e5-9bd3-49b77349fd68.jpg)
Я имел в виду пагинацию, которая снизу страницы. Она сейчас получается к подразделам не привязана, а сквозная по всему разделу.

**Comment by cinic** [comment]
![bcs broker landing page - structured bonds 2015-10-07 14-12-11](https://cloud.githubusercontent.com/assets/67061/10335961/af5c42ce-6cfd-11e5-90d7-a4e39ac40998.jpg)
Теперь для каждой вкладки своя пагинация
